/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadzone.menu;

/**
 *
 * @author franc
 */
public class OnlinePause extends javax.swing.JFrame {
    
    PauseMenu pm;

    /**
     * Creates new form OnlinePause
     */
    public OnlinePause(PauseMenu pm) {
        this.pm = pm;
        initComponents();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScorebardPane = new javax.swing.JScrollPane();
        jOnlinePane = new javax.swing.JScrollPane();

        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(768, 575));
        setMinimumSize(new java.awt.Dimension(768, 575));
        setPreferredSize(new java.awt.Dimension(768, 575));
        setResizable(false);
        setSize(new java.awt.Dimension(768, 575));
        getContentPane().setLayout(null);
        getContentPane().add(jScorebardPane);
        jScorebardPane.setBounds(0, 0, 219, 480);
        getContentPane().add(jOnlinePane);
        jOnlinePane.setBounds(226, 102, 100, 100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jOnlinePane;
    private javax.swing.JScrollPane jScorebardPane;
    // End of variables declaration//GEN-END:variables
}
