/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadzone.menu;

import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import deadzone.sprite.animated.Player;
import deadzone.utilities.Assets;
import deadzone.utilities.Database;

/**
 *
 * @author niko
 */
public class PauseMenu extends javax.swing.JDialog {

    /**
     * Creates new form PauseMenu
     */
    private static boolean pause;
    public static final Object PAUSELOCK = new Object();
    public static boolean end;
    private Player player;

    public PauseMenu(java.awt.Frame parent, boolean modal, Player player) {
        super(parent, modal);
        this.player = player;
        initComponents();
        setPause(true);
        end = false;
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        int x = (int) rect.getMaxX() / 2 - this.getWidth() / 2;
        int y = (int) rect.getMaxY() / 2 - this.getHeight() / 2;
        this.setLocation(x, y);

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                setPause(false);
            }
        });
    }

    public static boolean isPause() {
        return pause;
    }

    public static void setPause(boolean pause) {
        synchronized (PAUSELOCK) {
            PauseMenu.pause = pause;
            PAUSELOCK.notifyAll();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Resume = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAUSE");

        Resume.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Resume.setText("Resume");
        Resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });

        Settings.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Settings.setText("Settings");
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resume, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(Resume)
                .addGap(50, 50, 50)
                .addComponent(Settings)
                .addGap(54, 54, 54)
                .addComponent(Exit)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeActionPerformed
        // TODO add your handling code here:
        setPause(false);
        this.dispose();
    }//GEN-LAST:event_ResumeActionPerformed

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(SwingUtilities.getWindowAncestor(this));
        Settings set = new Settings(topFrame, true);
        set.setVisible(true);
    }//GEN-LAST:event_SettingsActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        end = true;
        setPause(false);
        if (Database.online) {
            Assets.ThreadOttieniScoreboard t2 = new Assets.ThreadOttieniScoreboard();
            t2.start();
            ThreadCancellaOnline t = new ThreadCancellaOnline();
            t.start();

        }

        synchronized (Assets.ThreadOttieniScoreboard.TOS) {
            if (Assets.ThreadOttieniScoreboard.occupato) {
                System.out.println("SE ESCE PRIMA DI Disconnesso contattare Ciccio");
                try {
                    System.out.println("Sono occupato");
                    Assets.ThreadOttieniScoreboard.TOS.wait();
                } catch (InterruptedException ex) {
                    Logger.getLogger(PauseMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.dispose();
        Menu menu = new Menu();
        MapFrame.gameMusic.stopSound();
        Menu.gameMusic.loopSound();
        menu.setVisible(true);
    }//GEN-LAST:event_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Resume;
    private javax.swing.JButton Settings;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public class ThreadCancellaOnline extends Thread {

        @Override
        public void run() {
            System.out.println("Sto rimuovendo dagli online");
            Database.CancellaOnline(player.getOnlineID());
        }
    }
}
